spring.application.name=zti
# Polaczenie z PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/products_db
spring.datasource.username=postgres
spring.datasource.password=password

# Automatyczne tworzenie tabel na podstawie encji
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# formatowanie logów w konsoli
spring.jpa.properties.hibernate.format_sql=true

# maksymalny rozmiar zdjecia
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB