spring.application.name=zti
# Po??czenie z PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/products_db
spring.datasource.username=postgres
spring.datasource.password=password

# Automatyczne tworzenie tabel na podstawie encji (odpowiednik migrations:migrate)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Opcjonalne: ?adniejsze formatowanie logów w konsoli
spring.jpa.properties.hibernate.format_sql=true